import type React from "react";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata, Viewport } from "next";
import { Onest } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./provider";
import PWAInstaller from "@/components/installPWA";
import NotificationWrapper from "@/components/notification-wrapper";

const onest = localFont({
  src: "./fonts/Onest-VariableFont_wght.ttf", 
  variable: "--font-sans",
  display: "swap",
});

const hostGrotesk = localFont({
  src: "./fonts/HostGrotesk-VariableFont_wght.ttf", 
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Task Reminder MVP",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#000000" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${onest.variable} ${hostGrotesk.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            {children}
            <Toaster />
            <PWAInstaller />
            <NotificationWrapper />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
